# Generated by Django 6.1 on 2026-08-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва торта')),
                ('image', models.ImageField(upload_to='cakes/', verbose_name='Зображення')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базова ціна')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торти',
            },
        ),
    ]
