# Generated by Django 6.1 on 2026-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_weight', models.PositiveIntegerField(default=2, verbose_name='Мінімальна вага замовлення (кг)')),
                ('two_tier_min_weight', models.PositiveIntegerField(default=4, verbose_name='Мін. вага двоповерхового (кг)')),
                ('different_fillings_min_weight', models.PositiveIntegerField(default=5, verbose_name='Мін. вага для різних начинок (кг)')),
                ('tier_construction_price', models.PositiveIntegerField(default=250, verbose_name='Ціна конструкції для ярусного (грн)')),
                ('weight_tolerance', models.PositiveIntegerField(default=300, verbose_name='Похибка ваги (+/- г)')),
                ('portion_weight', models.PositiveIntegerField(default=200, verbose_name='Розрахунок на людину (+/- г)')),
                ('velour_price_per_kg', models.PositiveIntegerField(default=200, verbose_name='Ціна велюрового покриття (грн/кг)')),
            ],
            options={
                'verbose_name': 'Налаштування правил',
                'verbose_name_plural': 'Налаштування правил',
            },
        ),
    ]
