# Generated by Django 6.1 on 2026-08-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rulesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва начинки')),
            ],
            options={
                'verbose_name': 'Начинка',
                'verbose_name_plural': 'Начинки',
            },
        ),
        migrations.AddField(
            model_name='rulesettings',
            name='bento_1kg_price',
            field=models.PositiveIntegerField(default=1100, verbose_name='Ціна бенто 1 кг (грн)'),
        ),
        migrations.AddField(
            model_name='rulesettings',
            name='bento_price',
            field=models.PositiveIntegerField(default=750, verbose_name='Ціна бенто торта (грн)'),
        ),
        migrations.AddField(
            model_name='rulesettings',
            name='trifle_price',
            field=models.PositiveIntegerField(default=150, verbose_name='Ціна трайфлу (грн/шт)'),
        ),
    ]
