# Generated by Django 6.1 on 2026-08-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_filling_rulesettings_bento_1kg_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(blank=True, verbose_name='Посилання на Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Посилання на Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Посилання на Facebook')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Номер телефону')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
