# Generated by Django 6.1 on 2026-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='cakes/previews/', verbose_name='Картинка для каталогу'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(upload_to='cakes/', verbose_name='Картинка для детального огляду товару'),
        ),
    ]
